<a href="https://colab.research.google.com/github/vartikatrao/BFS-DFS-Visualizer/blob/main/pytorch_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Mon Jun 19 09:24:11 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [3]:
random_tensor= torch.rand(3,4)

In [4]:
random_tensor

tensor([[0.3113, 0.0774, 0.2419, 0.4741],
        [0.1378, 0.9893, 0.3238, 0.3651],
        [0.9044, 0.6016, 0.4728, 0.1202]])

In [5]:
random_tensor.ndim

2

In [6]:
random_tensor=torch.rand_like(random_tensor)

In [7]:
random_tensor

tensor([[0.0591, 0.1381, 0.2958, 0.7976],
        [0.8023, 0.2328, 0.6241, 0.0079],
        [0.7595, 0.9676, 0.5326, 0.4812]])

In [8]:
zero_list= torch.zeros_like(random_tensor)

In [9]:
zero_list

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
one_to_ten= torch.arange(start=0, end=10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [11]:
#attributes of tensors
#dtype, device, shapes

In [12]:
#matrix Multiplication
tensor_A= torch.tensor([[1,2],[3,4], [5,6]])
tensor_A.shape

torch.Size([3, 2])

In [13]:
tensor_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [14]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [15]:
torch.mm(tensor_A, tensor_A.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

## Aggregation

In [16]:
x= torch.arange(0,100,10)
x
x.dtype

torch.int64

In [17]:
#find min
torch.min(x)


tensor(0)

In [18]:
x.max()

tensor(90)

In [19]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [20]:
x.type(torch.float32).mean()

tensor(45.)

In [21]:
device= "cuda" if torch.cuda.is_available() else "cpu"

In [22]:
device

'cuda'

In [23]:
torch.cuda.device_count()

1